import Head from 'next/head'
import Layout from '../components/Layout'

export default function Home() {
	return (
		<>
			<Head>
				<title>Blogr Landing Page</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.png" />
			</Head>
			<Layout>
				<div className='container'>
					<h1 className='title'>Hola Mundo</h1>
					<p>Lorem Ipsum Dolor Siamet Un</p>
				</div>
			</Layout>
		</>
	)
}
