import Head from 'next/head'
import Header from '../components/Header'
import Layout from '../components/Layout'
import { MenuInfo } from '../api/menu'

export default function Home() {
	return (
		<>
			<Head>
				<title>Blogr Landing Page</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.png" />
			</Head>
			<Layout>
				<section className="hero is-large hero-banner">
					<div className='hero-head'>
						<Header information={MenuInfo} />
					</div>
					<div className="hero-body has-text-centered">
						<h1><strong>A modern publishing platform</strong></h1>
						<p className='has-text-white'>Grow your audience and build your online brand</p>
						<div className="buttons is-centered my-5">
							<button className="button is-primary">Start fro Free</button>
							<button className="button is-secondary">Learn More</button>
						</div>
					</div>
				</section>
			</Layout>
		</>
	)
}
